### ISSUE TITLE
Missing download monitor file

### ISSUE THREAD

**Issue by mick9** [caarmen/network-monitor#116]
Description:
------------
The speed download test specifies 
https://github.com/caarmen/network-monitor/archive/netmon-1.12.2.zip
as the target.
The archive directory seems not to exist, so the test cannot work.

Steps to reproduce:
-------------------
Select Advanced Options => Speed Test => Download Test to see the URL.
Browse to https://github.com/caarmen/network-monitor/ and see that the URL target does not exist.  

Stacktrace (if reporting a crash):
----------------------------------
not applicable

Environment:
------------
* Android version: 7.0
* Device model:  Samsung Galaxy J5
* App version: v1.30.1
* App downloaded from (play store, f-droid, github, other):Play Store

**Comment by ypid** [comment]
@mick9 Can you recheck? I just tested it and it works for me.

**Comment by mick9** [comment]
It is visible now and download succeeded,
