### ISSUE TITLE
Add the speed test feature on the network monitor application 1.31.1

### ISSUE THREAD

**Issue by ammarraisafti** [caarmen/network-monitor#126]
# Introduction
Network Monitor is a diagnostic tool which periodically tests your network connection and logs the results to a database on the phone.  The goal of the app is to identify which cell towers around you may have connection problems.  

**Repository**
https://github.com/caarmen/network-monitor

# Components
The components (Features) I want to suggest is:

* Speed test.

Network monitors have very good functions. However, I think, this application still needs to be developed to make this application more interesting to use.

Therefore, I want to suggest new features for this application. I hope, developers can implement this suggestion into the application, making this application more attractive to use, and increasing in number of users.

# Proposal description
Developers should add this feature in the menu options available. And modify the section to give users the choice to start testing the network, and choose the available hosts. And give users detailed information about the results of network speeds that have been tested.

# Mockups / Examples
![Screenshot_2019-04-05-14-42-30-picsay.jpg](https://cdn.steemitimages.com/DQmQynftQZd89usQiCuBFa26bDKP9MenobLtmp6gNByvZnQ/Screenshot_2019-04-05-14-42-30-picsay.jpg)

![Screenshot_2019-04-05-15-13-37-picsay.jpg](https://cdn.steemitimages.com/DQmZTL2pCsxpGCMNQ8tqntufrnCgiK3U7RfGf87e91AHyBC/Screenshot_2019-04-05-15-13-37-picsay.jpg)

![Screenshot_2019-04-05-15-14-57-picsay.jpg](https://cdn.steemitimages.com/DQmPFSCRSEWiSAyrCiP3hJfHaRrAMrTA5jKp8ednHF7Dpia/Screenshot_2019-04-05-15-14-57-picsay.jpg)

![Screenshot_2019-04-05-15-13-01-picsay.jpg](https://cdn.steemitimages.com/DQmUCBBJBywukCiWPaC7XhMuLv9ANjAfAQ5gidv7iLZcENW/Screenshot_2019-04-05-15-13-01-picsay.jpg)

# Benefits
With the speed test feature on network monitor applications, users can test network speed on their devices easily and quickly, they can choose available hosts and test them easily and quickly using this application, and users will get information about network speed. So users more interesting using this application. And users will give the best rating for this application, they will also invite other users to use this application, because they can test the network on their devices. And that is a big advantage for users and application developers.

**Comment by caarmen** [comment]
A speed test feature already exists in the app.
