### ISSUE TITLE
unable to send sceduled email

### ISSUE THREAD

**Issue by redge911** [caarmen/network-monitor#52]
Hello , 

im wondering if i am doing someting wrong because i am unable to send a email by the schedule option.
It give me a error unable to send email.

if y tried the option to send  manually the rapport , if y chose the google option every thing work.

P.S. iam shure that my email setting are ok

thank

**Comment by caarmen** [comment]
Hello, 

This is an issue with Gmail. Let me just paste the reply I sent to another user who recently had this issue:


Thanks for your feedback.


Are you trying to send mail from a gmail account?  I've noticed that this sometimes doesn't work unless you enable this "access for less secure apps" setting:https://www.google.com/settings/security/lesssecureapps


It seems that Google considers sending mail via smtp as "unsecure" (even if you use TLS or SSL!).  If you don't enable this setting, I believe you'll get mail delivery failure notifications.

Let me know if you need more help. 

BTW, disclaimer: please read the fine print on that link before you decide to allow "less secure apps" to access your Gmail.

**Comment by redge911** [comment]
Thanks a lot , everything is now working fine
