### ISSUE TITLE
clear or reset the log files

### ISSUE THREAD

**Issue by redge911** [caarmen/network-monitor#53]
Hello Caarmen, 

this is more a question then a problem (sorry if i am at the wrong place) . Is ther a way to automaticaly reset the log files ( just like the "clear log files" option.

i am using on a android minipc and i want to prevent from connecting a screen and a keyboard to the device to manualy clear the log files.

FYI, im able to connect by SSH and im able to delete the "CSV "files but that do not clear the log !

Thank in advance

Redge

**Comment by caarmen** [comment]
Hello, 

You can go to advanced options, and almost at the bottom there's an option "limit database size". It's not exactly the same thing as wiping the db periodically (or after sending reports by mail) but it will make sure the db doesn't grow infinitely. Basically once the db gets to the limit you choose, every time a new row(s) is added, the oldest row(s) are deleted,to make sure there are at most X rows. 

Cheers, 
Carmen.
