### ISSUE TITLE
Export to file on local storage

### ISSUE THREAD

**Issue by oliver** [caarmen/network-monitor#64]
Is there a way to save the database as CSV file to storage? The Share feature only allows to send the log via email or chat, or to save it to Google Drive.

(Ideally I'd like to send the log via HTTP to my custom server, but saving it to storage would be a nice start...)

**Comment by calvarez-ov** [comment]
Hi Oliver.

Currently you'd need another app installed, that saves shared content to storage. That app would appear in the list of apps to share to.

I should probably make network monitor implement this feature itself.  This issue can remain open for that.

I know, off the top of my head, of one app that would add this "save to storage" item in the list of apps... and it has absolutely nothing to do with network monitor, but just happens to be another app I've contributed to, which is Bikey: https://play.google.com/store/apps/details?id=org.jraf.android.bikey

There are probably more general apps out there as well, that do just the save to storage function.

**Comment by caarmen** [comment]
Hi Oliver.

Currently you'd need another app installed, that saves shared content to storage. That app would appear in the list of apps to share to.

I should probably make network monitor implement this feature itself.  This issue can remain open for that.

I know, off the top of my head, of one app that would add this "save to storage" item in the list of apps... and it has absolutely nothing to do with network monitor, but just happens to be another app I've contributed to, which is Bikey: https://play.google.com/store/apps/details?id=org.jraf.android.bikey

There are probably more general apps out there as well, that do just the save to storage function.

**Comment by caarmen** [comment]
In version 1.21.0 (which is being progressively released on the Play Store), when you export (to CSV, Excel, whatever), there will be a new item in the list of apps to manage the export: "Save to storage".  It will just save to the root of the external storage (SD card).

Maybe in a future iteration, it will prompt the user to choose a folder to save the file to, but for now it's just stored to the root.

I'll close this issue once the app is fully published on the Play Store.  In the meantime, you can download it from the "releases" page: https://github.com/caarmen/network-monitor/releases

**Comment by caarmen** [comment]
> Maybe in a future iteration, it will prompt the user to choose a folder to save the file to, but for now it's just stored to the root.

This will be in version 1.22.0 (maybe published next week).

**Comment by oliver** [comment]
Wow, that was really quick action! I've just tested 1.21.0 and it works great - many thanks!
