### ISSUE TITLE
Check if longitude/latitude can have better precision

### ISSUE THREAD

**Issue by caarmen** [caarmen/network-monitor#72]
(more numbers after the decimal point)

**Comment by andreasscherbaum** [comment]
Oh, I was loking for this exact feature. Tried to measure my Wi-Fi at home, but all locations had the same imprecise lat/lon coordinates in the logfile.

Any idea when this will be released in the Play Store?

Thanks,
Andreas

**Comment by caarmen** [comment]
The fix is in version 1.26.4 of the app, which until now, was only published to 50% of the Play Store (staged rollout).

I just increased the percentage to 100%.  It may take a few hours to be visible.

You may need to change the setting in Advanced Options -> Location accuracy.  There are now four options there instead of two.  I noticed that sometimes the values retrieved when using Google Play Services were not as precise as when not using Google Play services.  So now the user can choose if they want Google Play Services for location or not.  Previously if you had Google Play Services on your phone, it used it.
