### ISSUE TITLE
Option to hide notification icon

### ISSUE THREAD

**Issue by caarmen** [caarmen/network-monitor#94]
User request:

Add an option for the notification icon. All apps have such an option and the user chooses if wants to see it. Here the notification is enforced, it is not useful and takes space from the task bar. It is possible to have notifications without icon on task bar (low priority).

**Comment by caarmen** [comment]
Available in 1.29.0

**Comment by dsnz** [comment]
Hello,

I had asked this option and I see now that it does not work on Android 8.1 (Oreo) so I reopen this issue instead of making a new one.

**Comment by dsnz** [comment]
Hello,

I had asked this option and I see now that it does not work on Android 8.1 (Oreo) so I think this issue should be reopened instead of making a new one.
