### ISSUE TITLE
WIFI and mobile network history capability

### ISSUE THREAD

**Issue by dsnz** [caarmen/network-monitor#99]
Hello,

I had asked for the enhancement of issue #94 and I am glad you acted so swiftly. Also congratulations for the great work you do. I hope I have some free time in the future and I contribute too.

I would like to ask you for a very much needed feature that it would be great to implement or perhaps spin-off into a separate app. Let me explain.

I use your app not to check a connection but with the intent to check when (exact time) and to which WIFI station (name, ethernet address, and other info) my mobile connects or disconnects to. Same for mobile connection. I can do this because you provide the WIFI and mobile connection details along with many other data (even when no data connection is done).

But this approach is not very accurate because I have set the log every 5 minutes in order to conserve cpu/log size etc., it is not so practical (I have to wade thru the log and trim it regularly and if I forget to do this and the log grows big, I'm in trouble)  and also it is not efficient in the end.

Believe me, this is a very much needed and useful capability for many reasons. Just a single and indirect usage example is that I use it to record power grid failure and restart time :D (using apps that record mobile charging/discharging is not helpful because most are not working reliably and I must have the phone on the charger always; there are other uses too relating to mobile security).

In order to do this, you do not need to log periodically but rather catch the intents that indicate network connections or disconnections and record them. 

There is no other app that has this capability (well not exactly, there are 1-2 but don't work correctly).

This could be an extra feature of your current app (best with a separate log) or a new app (mostly a copy of the old with many things removed and just the new feature implemented and why not even include charging/discharging history :D).

I hope you implement it considering its usefulness, uniqueness and rather easy implementation.

**Comment by caarmen** [comment]
Hello,

You can set "When the network changes" as the log frequency.  It's the
first option in the list of log frequencies. Then the app should add a log
entry each time the network connectivity or type changes.  To be honest, on
my own phone (Huawei P9 Lite), I've had some issues with this feature (the
app seems to be killed by the system after a while), and haven't made time
yet to investigate it.  But maybe you can try it out and see if it works
for you?

Cheers,
Carmen

**Comment by dsnz** [comment]
Hello,

I don't know how I missed this option!
Perhaps because the option list is rather long and defaults to value in middle of list, I thought all the list consists of numerical time values while the interesting option you mentioned was hidden at the start.

For me it seems to work okay though I get not one but a few log entries on network change (which is probably quite normal) and I have to evaluate it further.

At this moment this issue should be considered resolved and closed.

Thank you,
